apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: apps
spec:
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: apps
      version: 0.7.0
  interval: 1h
  values:
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-pvc
    postgresql:
      enabled: true
      image:
        repository: tensorchord/pgvecto-rs
        tag: pg14-v0.2.0
      global:
        postgresql:
          auth:
            username: immich
            database: immich
            password: immich
      primary:
        initdb:
          scripts:
            create-extensions.sql: |
              CREATE EXTENSION cube;
              CREATE EXTENSION earthdistance;
              CREATE EXTENSION vectors;
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
