apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-agent
  namespace: gitlab
spec:
  interval: 1h
  chart:
    spec:
      chart: gitlab-agent
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab
      version: v2.7.2
  values:
    config:
      kasAddress: wss://kas.gitlab.com
      secretName: gitlab-agent-token
