apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  chart:
    spec:
      chart: uptime-kuma
      sourceRef:
        kind: HelmRepository
        name: k3
        namespace: monitoring
      version: 1.3.6
  interval: 1h
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        traefik.ingress.kubernetes.io/router.middlewares: "auth-ak-outpost-authentik-embedded-outpost@kubernetescrd"
      hosts:
        - host: uptime.homelab.haseebmajid.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - uptime.homelab.haseebmajid.dev
          secretName: uptime-haseebmajid-dev-tls
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 3310
      runAsGroup: 3310
      fsGroup: 3310
      fsGroupChangePolicy: "OnRootMismatch"
