apiVersion: v1
kind: Secret
metadata:
  name: ryot-oauth
  namespace: apps
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:LEJTsu9s/fak2BS6N06hlJ/GNGw5eW5gGDGCzNycIamRlf2A46Tz+A==,iv:0kbKb5AEI+z6lgGlfUI2ZT4V10cWIiAzdK7P8lmDibw=,tag:oQk75viAZFhmjrNlavf03Q==,type:str]
  client-secret: ENC[AES256_GCM,data:nO3MV587u7Rrg9sxoq6wlzZx6BLGFugz0yC+ahCJ0+i9VpY8ae0I8Pihd/LxwSEWqplqwXbzUYt+FP5xkSKRoVz3mCMCCCDo/sEG9J8a/TNqLUhwWGRMKRDkz0MIDvW0Vh0xxnqelSoVtFw/hY1kRSg86ub/hZAIxkEEuhmr83k=,iv:w4g9P2RmQYBmzrk4mtgEibaSgwfp0wapIIJ6RVb2HsE=,tag:ihuq8HtwFR6sNouGzMnMvQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lsvwl2p2u3977vs0jm9cd28dgdm4ey8u8qwe6zxz3q45szc0u5vq7hn57y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZzFyMUVtVEM4VnpGelk1
        Kzhqd0ttVWVadkNQYmZtNXg1c2J4M3JBN1dNCll3UXp0STJaMzJjc0V1eS9EUmRp
        NVltblNBMWNPOW16bUdzME5qUmVyeDQKLS0tIENRTC9IQzFoM0oyYitIZDVjKzJB
        c0tFVzl2Y3gvSzNZTHFkY2JiWTA5UU0K8T+IzLmtBk1aUHGBhAz+DdAIjAhLjI2p
        129AUJuM6AgJU1NSyt6BZdJffTWWsSmasp49rxpndsCbh4mQiei8dQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-20T21:02:33Z"
  mac: ENC[AES256_GCM,data:+DCBP7Pux+ThbSqJHeqiZvNOuecp2fnw9XitBkRtXkI6hhc/z/3Y0dwtMaLW++Oh1eGNDzm9InMEuRiVRSJYB8e5qoBMhrRX/lU8iDuy5PnxzEaVwWB/oozPUT4cHUE9A3Ra+12prhsj6APfRcxQts8g89t60rmghYV155OyFBw=,iv:u+UYzQDwPvmCfrmb4nq/mDXDPkzfInUTp4ToHxR1bYU=,tag:HKRqEBCeFG5Q/ymuXJWOeg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
