apiVersion: v1
kind: PersistentVolume
metadata:
  name: banterbus-pv
  namespace: dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: dev
    name: banterbus-pvc
  hostPath:
    path: /mnt/data/banterbus
