apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  chart:
    spec:
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab-runner
        namespace: gitlab
      version: 0.65.0
  interval: 1m0s
  values:
    gitlabUrl: https://gitlab.com
    rbac:
      create: true
    runners:
      secret: gitlab-runner-secret
      cache:
        secretName: minio-secret
      config: |
        [[runners]]
          [runners.cache]
            Type = "s3"
            Path = "runner"
            Shared = true
            [runners.cache.s3]
              ServerAddress = "minio.gitlab.svc.cluster.local:9000"
              BucketName = "gitlab-runner"
              Insecure = true
              AuthenticationType = "access-key"
          [runners.kubernetes]
            image = "ubuntu:24.04"
            privileged = true
          [[runners.kubernetes.volumes.host_path]]
            name = "docker-socket"
            mount_path = "/var/run/docker.sock"
            host_path = "/var/run/docker.sock"
            read_Only = true
          [[runners.kubernetes.volumes.empty_dir]]
            name = "docker-certs"
            mount_path = "/var/run"
            medium = "Memory"
