apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: gitlab
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: gitlab
      version: 5.2.0
  interval: 1h
  values:
    replicas: 2
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 20Gi

    oidc:
      enabled: true
      configUrl: "https://auth.homelab.haseebmajid.dev/application/o/minio/.well-known/openid-configuration"
      existingClientSecretName: "minio-oauth"
      existingClientIdKey: "client-id"
      existingClientSecretKey: "client-secret"
      scopes: "openid,profile,email,minio"
      redirectUri: "https://console.minio.homelab.haseebmajid.dev/oauth_callback"

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      path: /
      hosts:
        - minio.homelab.haseebmajid.dev
      tls:
        - hosts:
            - minio.homelab.haseebmajid.dev
          secretName: minio-haseebmajid-dev-tls
    consoleIngress:
      enabled: true
      ingressClassName: traefik
      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - console.minio.homelab.haseebmajid.dev
      tls:
        - hosts:
            - console.minio.homelab.haseebmajid.dev
          secretName: console-minio-haseebmajid-dev-tls
