apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-banterbus.games
  namespace: kube-system
spec:
  secretName: wildcard-banterbus.games-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.banterbus.games"
