apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth
  namespace: monitoring
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:WxnQmogAoS9MtHHt/EuKnGXa0PUCvDzvQ/F/Mkrf7yTDwpFAqTa4og==,iv:O4JtxSSQ8sZBb/sBZn9JrFc462rhQeS2w602uk34gMM=,tag:a987whA+Ao5Lo0zFS7kI+g==,type:str]
  client-secret: ENC[AES256_GCM,data:KYgrX/4DBgStMxd3rMY8Wn11Y9xsHJz9ygImVrNDru3pX4Ek5SE/pCW8S2VbZW9tsvtWRSjm/lviEdBi02oLynCZiTJuAIhvIw3ezvc4P1Cr6Bj8hL+5YdtvMLXzQNAzsAoBMRZeB2Tec4cr99TjldiAiIKW6HTH8E45PKwV9kc=,iv:NUxOW643BEI30Nxi6xjHJ/wnQ7ykpyEslc3CWugEVW8=,tag:+W/V+RCkw/4/ME8PFUap6Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lsvwl2p2u3977vs0jm9cd28dgdm4ey8u8qwe6zxz3q45szc0u5vq7hn57y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZG5HYjl3ZUROQ2dPdkcy
        TVNpWHlCd00yT2lCZVZ5RHdXRE9aQnpxbEJBCk9XSVkrb1JJODlvR0lUelA4b0xX
        SERCejhEbFl1Yk83MWRXZWhwVlUyKzgKLS0tIDFMVUpWR3NKMURpeTFGMjNUaWNa
        amJDVlpvMndGdzBuS2ZaM1o0L3pCcDgKbmQXwGwO0WMYjsN3g6XDLgYF3dqto7iz
        umeKctMynKT7mrJsZiRYFZaY8kDF7dtNpiSycWmpCTDJEJU0bPgCjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-23T20:46:42Z"
  mac: ENC[AES256_GCM,data:0qPOINGj7t0e9YLP/MkrB+R8hLHzOLyQEkEJ5Fi0qtsluRO1LP8j5zmanZRb/O89E8VMi466p8geayyQN3TEKAAFnU4n3mCJ0ksb6yNzu0RkcobiOZ75GQXVTwJzOpT1JHUxUP8medQIoH4FZMmysYWZ+ISvEm8CeaS+Q1SAIuI=,iv:WSD49g9SKXPdJzDhfsWacP+0qNzIsXKdkDcUz4BKvzU=,tag:9xY6xhxv+TXBuB6vLDbL6w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
