apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: auth
      version: 2024.4.2
  interval: 1h
  values:
    worker:
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: secret_key
    server:
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - auth.homelab.haseebmajid.dev
        tls:
          - hosts:
              - auth.homelab.haseebmajid.dev
            secretName: auth-haseebmajid-dev-tls
      env:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: secret_key
    authentik:
      postgresql:
        password: "ThisIsNotASecurePassword"
    postgresql:
      enabled: true
      auth:
        password: "ThisIsNotASecurePassword"
    redis:
      enabled: true
