apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: database
spec:
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: database
      version: 0.0.9
  interval: 1h
  values:
    pooler:
      enabled: true
      monitoring:
        enablePodMonitor: true
